const data = [{"name": "Suya", "location": "", "menu":[
    "Beef Skewers", "Chicken Skewers", "Grilled Veggies Skewers", "Prawn Skewers", "Tilapia Fillet",
    "Grilled Corn", "Roasted Potatoes", "Steamed Veggies", "Seasoned Rice", "Grilled Plantains", "Sweet Potato Chips", "Mixed Green Salad",
    "Entree Salad", "Wrap",
    "Tilapia Special", "Jamaican-Style Patties",
    "Ginger Beer", "Water", "Ting", "Coke", "Diet Coke", "Sunkist", "Sprite"]},
    {"name": "Sliver", "location": "", "menu":["Pizza of the day", "Salad"]},
    {"name": "Bongo Burger","location": "","menu":[ "'All American' Burger", "Turkey Burger", "Mushroom Burger", "Bacon Burger", "Polish Sausage", "Hot Dog",
        "S/M/L Soda",
        "Shish Kabab Sandwich", "Chicken Sandwich", "Persian Burger Sandwich", "Half-Persian Burger Sandwich", "Steak Sandwich",
        "Full/Half Falafel",
        "Bongo Salad", "Homefries"]},
    {"name": "Saigon Express","location": "","menu":[ "Ham/Meat Pie/Grilled Chicken/Grilled Pork/Veggie Sandwich/Tofu/Fishcake",
        "Beef/Chicken Pho"]},
    {"name": "Fresco","location": "","menu":[ "Taco/Burrito/Quesadilla/Plate: Steak, Chicken, Carnitas, Veggie, Fish, Beans, Salsa, Cheese, Guac",
        "Tortilla Chips", "Water", "Soda"]},
    {"name": "Arinell's","location": "","menu":[ "Neopolitan (regular)", "Sicilian (deep dish)", "Vegan Slice",
        "Various toppings",
        "S/L: Coke, Diet Coke, Sprite, Root Beer, Fruit Punch, Lemonade"]}
];